---
- name: cicd
  hosts: devserver
  tasks:
   - name: download jenkins
     shell: "{{item}}"
     with_items:
      - wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
      - echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list
   - name: install jenkins
     apt:
      name: "{{item}}"
      state: present
      update_cache: "{{item}}"
     with_items:
      - {a: open jdk-8-jdk,b: yes}
      - {a: jenkins,b: no}
      - {a: git,b: no}
      - {a: maven,b: no}
- name: install tomcat8 and tomcat8-admin
  hosts: servers
  tasks:
   - name: install tomcat8 and tomcat8-admin
     apt:
      name: "{{item}}"
      state: present
      update_cache: yes
     with_items:
      - tomcat8
      - tomcat8-admin
- name: copy tomcat-users.xml
  hosts: servers
  tasks:
   - name: copy file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat8
...
